"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['zipRenamer.pyw']
DATA_FILES = ["zipRenamerMainWindow.ui", "preferencesDialog.ui", "rootSelectDialog.ui", "images/restartIcon.png", "images/restartIcon.png", "images/zipRenamer.png", "images/Gear-icon-291x300.png", "CFE.icns"]
OPTIONS = {
    'iconfile':'CFE.icns',
    'plist': {'CFBundleShortVersionString':'0.1.0',}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
