"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['zipRenamer.pyw']
DATA_FILES = ["zipRenamerMainWindow.ui", "preferencesDialog.ui", "rootSelectDialog.ui",  "helpDialog.ui", "images/questionMark.png", "images/zipRenamer.png", "images/gearIcon.png", "images/zipRenamer.icns", "helpDialog.html",]
OPTIONS = {
    'iconfile':'images/zipRenamer.icns',
    'plist': {'CFBundleShortVersionString':'0.1.0',}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
