"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['groupSelector.pyw']
DATA_FILES = ["groupSelectorMainWindow.ui",
              "preferencesDialog.ui",
              "rootSelectDialog.ui",
              "helpDialog.ui",
              "images/questionMark.png",
              "images/groupSelector.png",
              "images/gearIcon.png",
              "images/groupSelector.icns",
              "helpDialog.html",
              ]
OPTIONS = {
    'iconfile':'images/groupSelector.icns',
    'plist': {'CFBundleShortVersionString':'1.1.0',}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
